   name: Run Node.js Project Hourly

   on:
     schedule:
       - cron: '0 * * * *'  # Executa a cada uma hora

   jobs:
     run-script:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '14'  # Substitua pela versão que você precisa

       - name: Install dependencies
         run: npm install

       - name: Run script
         run: node index.js  # Substitua pelo seu script principal, se não for index.js
  
